//! Picks the Claude Code quota up out of a statusLine sidecar.
//!
//! Claude Code pipes a JSON blob to whatever `statusLine.command` is
//! configured, and that blob carries `rate_limits` for subscription accounts.
//! It is the only documented way to reach the number — hooks do not carry it —
//! so AuricIDE hands its own agents a `--settings` file pointing at a small
//! script that drops the blob somewhere readable.
//!
//! Three things keep that from being invasive:
//!
//! * `--settings` **merges**. Verified by hand against `claude` 2.1.233:
//!   `claude --settings <only-a-statusLine> mcp list` lists exactly the same
//!   servers as without it. The user's hooks, permissions and `env` are
//!   untouched; only the `statusLine` key is replaced.
//! * The script hands the payload on to whatever status line the user already
//!   had, so theirs does not vanish inside AuricIDE.
//! * That delegate is read from `~/.claude/settings.json` **only**. Project
//!   settings are a repo-controlled file, and Claude Code deliberately gates
//!   them behind its own folder-trust flow. Resolving them here and running
//!   what they name would execute repo-supplied code on the first agent spawn
//!   in a freshly cloned repo.
//!
//! What this cannot do: headless agents (`claude -p`) render no TUI and so
//! never call a statusLine, and nothing arrives while no AuricIDE agent is
//! running. The reading is a by-product of interactive runs and can be
//! arbitrarily old, which is why every surface that shows it also shows its age.

use std::fs;
use std::path::{Path, PathBuf};

use super::contract::{
    normalize_claude, parse_wire, ClaudeStatusLinePayload, UsageError, UsageSnapshot,
};

const SOURCE: &str = "claude";

/// Bumped when the generated script changes shape. The artifacts are compared
/// by content, so this only has to be readable by a human wondering which
/// version wrote the file in front of them.
const ARTIFACT_VERSION: u32 = 1;

/// How often Claude Code re-runs the status line while a session sits idle.
///
/// The event-driven ticks go quiet when nothing changes, so without this the
/// number freezes while an agent waits on a subagent. 45s rather than the
/// tempting 10: this is a shell fork plus a file write *per running agent*, for
/// a figure that moves on a five-hour scale.
const REFRESH_INTERVAL_SECS: u32 = 45;

/// The generated script. Kept as a constant rather than assembled with
/// `format!` so it can be read and reviewed as the shell it actually is.
const STATUSLINE_SCRIPT: &str = r#"#!/bin/sh
# auric-usage-statusline v1 — generated by AuricIDE, safe to delete.
#
# Claude Code pipes its status-line JSON to this script on stdin. The script
# drops that JSON where AuricIDE can read it and then hands the same input to
# whichever status line was configured before, so the user's own one survives.
#
#   $1  where to drop the payload
#   $2  the previously configured statusLine command, or empty

drop="$1"
delegate="$2"

payload=$(cat)

# A per-process temp name, not a shared one: several agents run this script at
# the same time, and one fixed name would let two writers truncate each other
# and then rename half a file into place.
tmp="$drop.$$.tmp"
printf '%s' "$payload" > "$tmp" 2>/dev/null && mv -f "$tmp" "$drop" 2>/dev/null
rm -f "$tmp" 2>/dev/null

# stdin has been drained by now, so the delegate has to be handed the payload
# again — reading EOF would blank the user's status line instead of rendering it.
if [ -n "$delegate" ]; then
  printf '%s' "$payload" | /bin/sh -c "$delegate"
fi

exit 0
"#;

fn artifact_dir(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join("usage-limits")
}

fn script_path_in(app_data_dir: &Path) -> PathBuf {
    artifact_dir(app_data_dir).join("statusline.sh")
}

fn settings_path_in(app_data_dir: &Path) -> PathBuf {
    artifact_dir(app_data_dir).join("claude-settings.json")
}

/// Escapes a value for use inside single quotes in `sh`.
fn shell_escape_single_quoted(value: &str) -> String {
    value.replace('\'', r"'\''")
}

/// The `statusLine.command` line.
///
/// Invoked as `/bin/sh <script>` rather than executed directly, so the script
/// needs no execute bit — a missing `+x` is the single most common reason a
/// status line never appears, and it survives umasks and restored backups in
/// ways that are hard to spot afterwards.
pub fn render_statusline_command(script: &Path, drop: &Path, delegate: Option<&str>) -> String {
    format!(
        "/bin/sh '{}' '{}' '{}'",
        shell_escape_single_quoted(&script.display().to_string()),
        shell_escape_single_quoted(&drop.display().to_string()),
        shell_escape_single_quoted(delegate.unwrap_or_default()),
    )
}

/// The settings file handed to `claude --settings`.
pub fn render_settings(command: &str) -> String {
    let value = serde_json::json!({
        "_auricVersion": ARTIFACT_VERSION,
        "statusLine": {
            "type": "command",
            "command": command,
            "refreshInterval": REFRESH_INTERVAL_SECS,
        }
    });
    serde_json::to_string_pretty(&value).unwrap_or_default()
}

/// Reads the status line the user had configured, so the sidecar can hand the
/// payload on instead of replacing it with nothing.
///
/// Only `~/.claude/settings.json` — see the module docs for why project
/// settings are deliberately not consulted.
pub fn resolve_delegate(user_settings_json: &str) -> Option<String> {
    let value: serde_json::Value = serde_json::from_str(user_settings_json).ok()?;
    let status_line = value.get("statusLine")?;
    if status_line.get("type").and_then(serde_json::Value::as_str) != Some("command") {
        return None;
    }
    let command = status_line.get("command")?.as_str()?.trim();
    if command.is_empty() {
        None
    } else {
        Some(command.to_string())
    }
}

fn user_settings_path() -> Option<PathBuf> {
    std::env::var_os("HOME").map(|home| PathBuf::from(home).join(".claude/settings.json"))
}

/// Writes the two artifacts if they are missing or out of date, and returns the
/// settings file to hand to `claude --settings`.
///
/// Content comparison rather than a version check, because the command line
/// also changes when the user's own status line does. Nothing is written when
/// the content already matches, so two agents starting at once do not rewrite
/// a file the other one is reading.
pub fn ensure_sidecar(app_data_dir: &Path, delegate: Option<&str>) -> Result<PathBuf, String> {
    let dir = artifact_dir(app_data_dir);
    fs::create_dir_all(&dir).map_err(|error| error.to_string())?;

    let script = script_path_in(app_data_dir);
    write_if_changed(&script, STATUSLINE_SCRIPT)?;

    let drop = super::store::claude_drop_path_in(app_data_dir);
    let settings = settings_path_in(app_data_dir);
    let body = render_settings(&render_statusline_command(&script, &drop, delegate));
    write_if_changed(&settings, &body)?;

    Ok(settings)
}

/// Same as [`ensure_sidecar`], resolving the delegate from the user's own
/// Claude Code settings.
pub fn ensure_sidecar_for_user(app_data_dir: &Path) -> Result<PathBuf, String> {
    let delegate = user_settings_path()
        .and_then(|path| fs::read_to_string(path).ok())
        .and_then(|body| resolve_delegate(&body));
    ensure_sidecar(app_data_dir, delegate.as_deref())
}

fn write_if_changed(path: &Path, contents: &str) -> Result<(), String> {
    if fs::read_to_string(path).is_ok_and(|existing| existing == contents) {
        return Ok(());
    }
    let temporary = path.with_extension("tmp");
    fs::write(&temporary, contents).map_err(|error| error.to_string())?;
    fs::rename(&temporary, path).map_err(|error| error.to_string())?;
    Ok(())
}

/// Turns one dropped payload into a snapshot.
pub fn ingest(body: &str, observed_at: i64) -> Result<UsageSnapshot, UsageError> {
    let payload: ClaudeStatusLinePayload = parse_wire(SOURCE, body)?;
    normalize_claude(payload, observed_at)
}

/// Reads the drop file, if the sidecar has written one yet.
pub fn ingest_drop(drop: &Path, observed_at: i64) -> Result<UsageSnapshot, UsageError> {
    let body = fs::read_to_string(drop).map_err(|error| UsageError::Unavailable {
        source: SOURCE.to_string(),
        detail: format!("no status-line payload yet ({error})"),
    })?;
    ingest(&body, observed_at)
}

#[cfg(test)]
mod tests {
    use super::*;

    const OBSERVED_AT: i64 = 1_787_300_000;

    // ── The generated command line ─────────────────────────────────────

    #[test]
    fn the_command_runs_the_script_through_sh_so_the_execute_bit_cannot_matter() {
        let command = render_statusline_command(
            Path::new("/tmp/a/statusline.sh"),
            Path::new("/tmp/a/drop.json"),
            None,
        );
        assert!(
            command.starts_with("/bin/sh '/tmp/a/statusline.sh'"),
            "{command}"
        );
    }

    #[test]
    fn a_path_with_spaces_survives_quoting() {
        // `Application Support` is in the real path on every Mac.
        let command = render_statusline_command(
            Path::new(
                "/Users/x/Library/Application Support/com.auricide.ide/usage-limits/statusline.sh",
            ),
            Path::new(
                "/Users/x/Library/Application Support/com.auricide.ide/usage-limits/drop.json",
            ),
            None,
        );
        assert!(
            command.contains("'/Users/x/Library/Application Support/"),
            "{command}"
        );
    }

    #[test]
    fn a_delegate_containing_a_quote_cannot_break_out_of_its_argument() {
        let command = render_statusline_command(
            Path::new("/tmp/s.sh"),
            Path::new("/tmp/d.json"),
            Some("echo 'hi'; rm -rf /"),
        );
        // The inner quotes are neutralised, so the whole delegate stays one
        // argument rather than becoming extra commands.
        assert!(command.contains(r"'\''hi'\''"), "{command}");
        assert!(!command.contains("'echo 'hi'"), "{command}");
    }

    #[test]
    fn the_settings_file_only_sets_the_status_line() {
        let body = render_settings("/bin/sh '/tmp/s.sh'");
        let value: serde_json::Value = serde_json::from_str(&body).unwrap();
        let keys: Vec<&String> = value.as_object().unwrap().keys().collect();
        // `--settings` merges, so anything extra here would override a user
        // setting for every agent AuricIDE starts.
        assert_eq!(keys, vec!["_auricVersion", "statusLine"]);
        assert_eq!(value["statusLine"]["type"], "command");
        assert_eq!(value["statusLine"]["refreshInterval"], 45);
    }

    // ── Delegate resolution ────────────────────────────────────────────

    #[test]
    fn an_existing_status_line_is_carried_over() {
        let settings =
            r#"{"model":"opus","statusLine":{"type":"command","command":"~/bin/mine.sh"}}"#;
        assert_eq!(resolve_delegate(settings).as_deref(), Some("~/bin/mine.sh"));
    }

    #[test]
    fn no_status_line_means_no_delegate() {
        for settings in [
            r#"{"model":"opus"}"#,
            r#"{"statusLine":{"type":"command","command":"   "}}"#,
            r#"{"statusLine":{"type":"static","text":"hi"}}"#,
            "not json at all",
        ] {
            assert_eq!(resolve_delegate(settings), None, "{settings}");
        }
    }

    // ── Artifacts on disk ──────────────────────────────────────────────

    #[test]
    fn the_sidecar_is_written_once_and_left_alone_afterwards() {
        let dir = tempfile::tempdir().unwrap();
        let first = ensure_sidecar(dir.path(), None).unwrap();
        let stamp = fs::metadata(&first).unwrap().modified().unwrap();

        // A rewrite while another agent's `claude` is reading the file is the
        // failure this guards against, so an unchanged run must not touch it.
        let second = ensure_sidecar(dir.path(), None).unwrap();
        assert_eq!(first, second);
        assert_eq!(fs::metadata(&second).unwrap().modified().unwrap(), stamp);
    }

    #[test]
    fn changing_the_delegate_rewrites_the_settings() {
        let dir = tempfile::tempdir().unwrap();
        ensure_sidecar(dir.path(), None).unwrap();
        let settings = ensure_sidecar(dir.path(), Some("~/bin/mine.sh")).unwrap();
        let body = fs::read_to_string(&settings).unwrap();
        assert!(body.contains("mine.sh"), "{body}");
    }

    #[test]
    fn a_hand_deleted_script_comes_back() {
        let dir = tempfile::tempdir().unwrap();
        ensure_sidecar(dir.path(), None).unwrap();
        let script = script_path_in(dir.path());
        fs::remove_file(&script).unwrap();

        ensure_sidecar(dir.path(), None).unwrap();
        assert!(script.exists());
    }

    #[test]
    fn writing_the_sidecar_leaves_no_temp_files_behind() {
        let dir = tempfile::tempdir().unwrap();
        ensure_sidecar(dir.path(), Some("~/bin/mine.sh")).unwrap();
        let leftovers: Vec<_> = fs::read_dir(artifact_dir(dir.path()))
            .unwrap()
            .filter_map(Result::ok)
            .filter(|entry| entry.file_name().to_string_lossy().ends_with(".tmp"))
            .collect();
        assert!(leftovers.is_empty());
    }

    // ── Ingestion ──────────────────────────────────────────────────────

    #[test]
    fn a_dropped_payload_becomes_a_snapshot() {
        let body = include_str!("../../../fixtures/usage-limits/claude.statusline.json");
        let snapshot = ingest(body, OBSERVED_AT).expect("subscription payload");
        assert_eq!(snapshot.provider, "claude");
        assert_eq!(snapshot.source, "statusline");
        assert_eq!(snapshot.windows.len(), 2);
    }

    #[test]
    fn an_api_key_account_reports_not_subscribed_rather_than_an_empty_reading() {
        let body =
            include_str!("../../../fixtures/usage-limits/claude.statusline.no-rate-limits.json");
        let error = ingest(body, OBSERVED_AT).expect_err("nothing to report");
        assert!(
            error.to_string().starts_with("USAGE_NOT_SUBSCRIBED:"),
            "{error}"
        );
    }

    #[test]
    fn a_missing_drop_file_is_unavailable_not_a_panic() {
        let dir = tempfile::tempdir().unwrap();
        let error = ingest_drop(&dir.path().join("nothing.json"), OBSERVED_AT)
            .expect_err("the sidecar has not run yet");
        assert!(
            error.to_string().starts_with("USAGE_UNAVAILABLE:"),
            "{error}"
        );
    }

    // ── The script itself ──────────────────────────────────────────────

    #[cfg(unix)]
    #[test]
    fn the_script_drops_the_payload_and_still_feeds_the_delegate() {
        use std::io::Write;
        use std::process::{Command, Stdio};

        let dir = tempfile::tempdir().unwrap();
        ensure_sidecar(dir.path(), None).unwrap();
        let script = script_path_in(dir.path());
        let drop = super::super::store::claude_drop_path_in(dir.path());
        let delegate_output = dir.path().join("delegate.txt");
        let delegate = format!("cat > '{}'", delegate_output.display());

        let payload = include_str!("../../../fixtures/usage-limits/claude.statusline.json");
        let mut child = Command::new("/bin/sh")
            .arg(&script)
            .arg(&drop)
            .arg(&delegate)
            .stdin(Stdio::piped())
            .stdout(Stdio::null())
            .spawn()
            .expect("script runs");
        child
            .stdin
            .take()
            .unwrap()
            .write_all(payload.as_bytes())
            .unwrap();
        assert!(child.wait().unwrap().success());

        // Dropped for us...
        let dropped = fs::read_to_string(&drop).expect("payload was dropped");
        assert!(ingest(&dropped, OBSERVED_AT).is_ok());

        // ...and handed on intact. Draining stdin without re-emitting it would
        // leave the user's own status line reading EOF and printing nothing.
        let delegated = fs::read_to_string(&delegate_output).expect("delegate was fed");
        assert_eq!(delegated.trim(), payload.trim());
    }

    #[cfg(unix)]
    #[test]
    fn the_script_needs_no_execute_bit() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        ensure_sidecar(dir.path(), None).unwrap();
        let script = script_path_in(dir.path());
        fs::set_permissions(&script, fs::Permissions::from_mode(0o600)).unwrap();

        let status = std::process::Command::new("/bin/sh")
            .arg(&script)
            .arg(dir.path().join("drop.json"))
            .arg("")
            .stdin(std::process::Stdio::null())
            .status()
            .expect("script runs through sh regardless of its mode");
        assert!(status.success());
    }
}
